//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("McPermissionsModel", "FK__PrEntries__world__68487DD7", "PrWorlds", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PermsManager.Models.PrWorld), "PrEntries", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PermsManager.Models.PrEntry), true)]
[assembly: EdmRelationshipAttribute("McPermissionsModel", "FK__PrPermiss__entry__6E01572D", "PrEntries", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PermsManager.Models.PrEntry), "PrPermissions", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PermsManager.Models.PrPermission), true)]
[assembly: EdmRelationshipAttribute("McPermissionsModel", "FK__PrTrackGrou__gid__08B54D69", "PrEntry", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PermsManager.Models.PrEntry), "PrTrackGroup", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PermsManager.Models.PrTrackGroup), true)]
[assembly: EdmRelationshipAttribute("McPermissionsModel", "FK__PrData__entryid__797309D9", "PrEntry", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PermsManager.Models.PrEntry), "PrData", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PermsManager.Models.PrData), true)]
[assembly: EdmRelationshipAttribute("McPermissionsModel", "FK__PrInherit__child__123EB7A3", "PrEntry", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PermsManager.Models.PrEntry), "PrInheritance", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PermsManager.Models.PrInheritance), true)]
[assembly: EdmRelationshipAttribute("McPermissionsModel", "FK__PrInherit__paren__1332DBDC", "PrEntry", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PermsManager.Models.PrEntry), "PrInheritance", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PermsManager.Models.PrInheritance), true)]
[assembly: EdmRelationshipAttribute("McPermissionsModel", "FK__PrWorldBa__defau__73BA3083", "PrEntry", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(PermsManager.Models.PrEntry), "PrWorldBase", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PermsManager.Models.PrWorldBase), true)]
[assembly: EdmRelationshipAttribute("McPermissionsModel", "FK__PrTrackGr__track__07C12930", "PrTrack", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PermsManager.Models.PrTrack), "PrTrackGroup", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PermsManager.Models.PrTrackGroup), true)]
[assembly: EdmRelationshipAttribute("McPermissionsModel", "FK__PrTracks__worldi__02084FDA", "PrWorld", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PermsManager.Models.PrWorld), "PrTrack", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PermsManager.Models.PrTrack), true)]
[assembly: EdmRelationshipAttribute("McPermissionsModel", "FK__PrWorldBa__world__72C60C4A", "PrWorld", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PermsManager.Models.PrWorld), "PrWorldBase", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(PermsManager.Models.PrWorldBase), true)]

#endregion

namespace PermsManager.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class McPermissonsEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new McPermissonsEntities object using the connection string found in the 'McPermissonsEntities' section of the application configuration file.
        /// </summary>
        public McPermissonsEntities() : base("name=McPermissonsEntities", "McPermissonsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new McPermissonsEntities object.
        /// </summary>
        public McPermissonsEntities(string connectionString) : base(connectionString, "McPermissonsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new McPermissonsEntities object.
        /// </summary>
        public McPermissonsEntities(EntityConnection connection) : base(connection, "McPermissonsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PrEntry> PrEntries
        {
            get
            {
                if ((_PrEntries == null))
                {
                    _PrEntries = base.CreateObjectSet<PrEntry>("PrEntries");
                }
                return _PrEntries;
            }
        }
        private ObjectSet<PrEntry> _PrEntries;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PrPermission> PrPermissions
        {
            get
            {
                if ((_PrPermissions == null))
                {
                    _PrPermissions = base.CreateObjectSet<PrPermission>("PrPermissions");
                }
                return _PrPermissions;
            }
        }
        private ObjectSet<PrPermission> _PrPermissions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PrWorld> PrWorlds
        {
            get
            {
                if ((_PrWorlds == null))
                {
                    _PrWorlds = base.CreateObjectSet<PrWorld>("PrWorlds");
                }
                return _PrWorlds;
            }
        }
        private ObjectSet<PrWorld> _PrWorlds;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PrTrackGroup> PrTrackGroups
        {
            get
            {
                if ((_PrTrackGroups == null))
                {
                    _PrTrackGroups = base.CreateObjectSet<PrTrackGroup>("PrTrackGroups");
                }
                return _PrTrackGroups;
            }
        }
        private ObjectSet<PrTrackGroup> _PrTrackGroups;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PrData> PrDatas
        {
            get
            {
                if ((_PrDatas == null))
                {
                    _PrDatas = base.CreateObjectSet<PrData>("PrDatas");
                }
                return _PrDatas;
            }
        }
        private ObjectSet<PrData> _PrDatas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PrInheritance> PrInheritances
        {
            get
            {
                if ((_PrInheritances == null))
                {
                    _PrInheritances = base.CreateObjectSet<PrInheritance>("PrInheritances");
                }
                return _PrInheritances;
            }
        }
        private ObjectSet<PrInheritance> _PrInheritances;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PrTrack> PrTracks
        {
            get
            {
                if ((_PrTracks == null))
                {
                    _PrTracks = base.CreateObjectSet<PrTrack>("PrTracks");
                }
                return _PrTracks;
            }
        }
        private ObjectSet<PrTrack> _PrTracks;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PrWorldBase> PrWorldBases
        {
            get
            {
                if ((_PrWorldBases == null))
                {
                    _PrWorldBases = base.CreateObjectSet<PrWorldBase>("PrWorldBases");
                }
                return _PrWorldBases;
            }
        }
        private ObjectSet<PrWorldBase> _PrWorldBases;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PrEntries EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPrEntries(PrEntry prEntry)
        {
            base.AddObject("PrEntries", prEntry);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PrPermissions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPrPermissions(PrPermission prPermission)
        {
            base.AddObject("PrPermissions", prPermission);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PrWorlds EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPrWorlds(PrWorld prWorld)
        {
            base.AddObject("PrWorlds", prWorld);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PrTrackGroups EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPrTrackGroups(PrTrackGroup prTrackGroup)
        {
            base.AddObject("PrTrackGroups", prTrackGroup);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PrDatas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPrDatas(PrData prData)
        {
            base.AddObject("PrDatas", prData);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PrInheritances EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPrInheritances(PrInheritance prInheritance)
        {
            base.AddObject("PrInheritances", prInheritance);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PrTracks EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPrTracks(PrTrack prTrack)
        {
            base.AddObject("PrTracks", prTrack);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PrWorldBases EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPrWorldBases(PrWorldBase prWorldBase)
        {
            base.AddObject("PrWorldBases", prWorldBase);
        }

        #endregion
        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="groupId">No Metadata Documentation available.</param>
        public ObjectResult<get_groupPlayers_Result> get_groupPlayers(Nullable<global::System.Int32> groupId)
        {
            ObjectParameter groupIdParameter;
            if (groupId.HasValue)
            {
                groupIdParameter = new ObjectParameter("groupId", groupId);
            }
            else
            {
                groupIdParameter = new ObjectParameter("groupId", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<get_groupPlayers_Result>("get_groupPlayers", groupIdParameter);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="McPermissionsModel", Name="PrData")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PrData : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PrData object.
        /// </summary>
        /// <param name="dataid">Initial value of the dataid property.</param>
        /// <param name="entryid">Initial value of the entryid property.</param>
        /// <param name="path">Initial value of the path property.</param>
        /// <param name="data">Initial value of the data property.</param>
        public static PrData CreatePrData(global::System.Int32 dataid, global::System.Int32 entryid, global::System.String path, global::System.String data)
        {
            PrData prData = new PrData();
            prData.dataid = dataid;
            prData.entryid = entryid;
            prData.path = path;
            prData.data = data;
            return prData;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 dataid
        {
            get
            {
                return _dataid;
            }
            set
            {
                if (_dataid != value)
                {
                    OndataidChanging(value);
                    ReportPropertyChanging("dataid");
                    _dataid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("dataid");
                    OndataidChanged();
                }
            }
        }
        private global::System.Int32 _dataid;
        partial void OndataidChanging(global::System.Int32 value);
        partial void OndataidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 entryid
        {
            get
            {
                return _entryid;
            }
            set
            {
                OnentryidChanging(value);
                ReportPropertyChanging("entryid");
                _entryid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("entryid");
                OnentryidChanged();
            }
        }
        private global::System.Int32 _entryid;
        partial void OnentryidChanging(global::System.Int32 value);
        partial void OnentryidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String path
        {
            get
            {
                return _path;
            }
            set
            {
                OnpathChanging(value);
                ReportPropertyChanging("path");
                _path = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("path");
                OnpathChanged();
            }
        }
        private global::System.String _path;
        partial void OnpathChanging(global::System.String value);
        partial void OnpathChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String data
        {
            get
            {
                return _data;
            }
            set
            {
                OndataChanging(value);
                ReportPropertyChanging("data");
                _data = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("data");
                OndataChanged();
            }
        }
        private global::System.String _data;
        partial void OndataChanging(global::System.String value);
        partial void OndataChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("McPermissionsModel", "FK__PrData__entryid__797309D9", "PrEntry")]
        public PrEntry PrEntry
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PrEntry>("McPermissionsModel.FK__PrData__entryid__797309D9", "PrEntry").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PrEntry>("McPermissionsModel.FK__PrData__entryid__797309D9", "PrEntry").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PrEntry> PrEntryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PrEntry>("McPermissionsModel.FK__PrData__entryid__797309D9", "PrEntry");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PrEntry>("McPermissionsModel.FK__PrData__entryid__797309D9", "PrEntry", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="McPermissionsModel", Name="PrEntry")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PrEntry : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PrEntry object.
        /// </summary>
        /// <param name="entryid">Initial value of the entryid property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="worldid">Initial value of the worldid property.</param>
        /// <param name="type">Initial value of the type property.</param>
        public static PrEntry CreatePrEntry(global::System.Int32 entryid, global::System.String name, global::System.Int32 worldid, global::System.Byte type)
        {
            PrEntry prEntry = new PrEntry();
            prEntry.entryid = entryid;
            prEntry.name = name;
            prEntry.worldid = worldid;
            prEntry.type = type;
            return prEntry;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 entryid
        {
            get
            {
                return _entryid;
            }
            set
            {
                if (_entryid != value)
                {
                    OnentryidChanging(value);
                    ReportPropertyChanging("entryid");
                    _entryid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("entryid");
                    OnentryidChanged();
                }
            }
        }
        private global::System.Int32 _entryid;
        partial void OnentryidChanging(global::System.Int32 value);
        partial void OnentryidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 worldid
        {
            get
            {
                return _worldid;
            }
            set
            {
                OnworldidChanging(value);
                ReportPropertyChanging("worldid");
                _worldid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("worldid");
                OnworldidChanged();
            }
        }
        private global::System.Int32 _worldid;
        partial void OnworldidChanging(global::System.Int32 value);
        partial void OnworldidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte type
        {
            get
            {
                return _type;
            }
            set
            {
                OntypeChanging(value);
                ReportPropertyChanging("type");
                _type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("type");
                OntypeChanged();
            }
        }
        private global::System.Byte _type;
        partial void OntypeChanging(global::System.Byte value);
        partial void OntypeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("McPermissionsModel", "FK__PrEntries__world__68487DD7", "PrWorlds")]
        public PrWorld PrWorld
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PrWorld>("McPermissionsModel.FK__PrEntries__world__68487DD7", "PrWorlds").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PrWorld>("McPermissionsModel.FK__PrEntries__world__68487DD7", "PrWorlds").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PrWorld> PrWorldReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PrWorld>("McPermissionsModel.FK__PrEntries__world__68487DD7", "PrWorlds");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PrWorld>("McPermissionsModel.FK__PrEntries__world__68487DD7", "PrWorlds", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("McPermissionsModel", "FK__PrPermiss__entry__6E01572D", "PrPermissions")]
        public EntityCollection<PrPermission> PrPermissions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PrPermission>("McPermissionsModel.FK__PrPermiss__entry__6E01572D", "PrPermissions");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PrPermission>("McPermissionsModel.FK__PrPermiss__entry__6E01572D", "PrPermissions", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("McPermissionsModel", "FK__PrTrackGrou__gid__08B54D69", "PrTrackGroup")]
        public EntityCollection<PrTrackGroup> PrTrackGroups
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PrTrackGroup>("McPermissionsModel.FK__PrTrackGrou__gid__08B54D69", "PrTrackGroup");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PrTrackGroup>("McPermissionsModel.FK__PrTrackGrou__gid__08B54D69", "PrTrackGroup", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("McPermissionsModel", "FK__PrData__entryid__797309D9", "PrData")]
        public EntityCollection<PrData> PrDatas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PrData>("McPermissionsModel.FK__PrData__entryid__797309D9", "PrData");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PrData>("McPermissionsModel.FK__PrData__entryid__797309D9", "PrData", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("McPermissionsModel", "FK__PrInherit__child__123EB7A3", "PrInheritance")]
        public EntityCollection<PrInheritance> PrInheritances
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PrInheritance>("McPermissionsModel.FK__PrInherit__child__123EB7A3", "PrInheritance");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PrInheritance>("McPermissionsModel.FK__PrInherit__child__123EB7A3", "PrInheritance", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("McPermissionsModel", "FK__PrInherit__paren__1332DBDC", "PrInheritance")]
        public EntityCollection<PrInheritance> PrInheritances1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PrInheritance>("McPermissionsModel.FK__PrInherit__paren__1332DBDC", "PrInheritance");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PrInheritance>("McPermissionsModel.FK__PrInherit__paren__1332DBDC", "PrInheritance", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("McPermissionsModel", "FK__PrWorldBa__defau__73BA3083", "PrWorldBase")]
        public EntityCollection<PrWorldBase> PrWorldBases
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PrWorldBase>("McPermissionsModel.FK__PrWorldBa__defau__73BA3083", "PrWorldBase");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PrWorldBase>("McPermissionsModel.FK__PrWorldBa__defau__73BA3083", "PrWorldBase", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="McPermissionsModel", Name="PrInheritance")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PrInheritance : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PrInheritance object.
        /// </summary>
        /// <param name="uinheritid">Initial value of the uinheritid property.</param>
        /// <param name="childid">Initial value of the childid property.</param>
        /// <param name="parentid">Initial value of the parentid property.</param>
        /// <param name="parentorder">Initial value of the parentorder property.</param>
        public static PrInheritance CreatePrInheritance(global::System.Int32 uinheritid, global::System.Int32 childid, global::System.Int32 parentid, global::System.Int32 parentorder)
        {
            PrInheritance prInheritance = new PrInheritance();
            prInheritance.uinheritid = uinheritid;
            prInheritance.childid = childid;
            prInheritance.parentid = parentid;
            prInheritance.parentorder = parentorder;
            return prInheritance;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 uinheritid
        {
            get
            {
                return _uinheritid;
            }
            set
            {
                if (_uinheritid != value)
                {
                    OnuinheritidChanging(value);
                    ReportPropertyChanging("uinheritid");
                    _uinheritid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("uinheritid");
                    OnuinheritidChanged();
                }
            }
        }
        private global::System.Int32 _uinheritid;
        partial void OnuinheritidChanging(global::System.Int32 value);
        partial void OnuinheritidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 childid
        {
            get
            {
                return _childid;
            }
            set
            {
                OnchildidChanging(value);
                ReportPropertyChanging("childid");
                _childid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("childid");
                OnchildidChanged();
            }
        }
        private global::System.Int32 _childid;
        partial void OnchildidChanging(global::System.Int32 value);
        partial void OnchildidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 parentid
        {
            get
            {
                return _parentid;
            }
            set
            {
                OnparentidChanging(value);
                ReportPropertyChanging("parentid");
                _parentid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("parentid");
                OnparentidChanged();
            }
        }
        private global::System.Int32 _parentid;
        partial void OnparentidChanging(global::System.Int32 value);
        partial void OnparentidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 parentorder
        {
            get
            {
                return _parentorder;
            }
            set
            {
                OnparentorderChanging(value);
                ReportPropertyChanging("parentorder");
                _parentorder = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("parentorder");
                OnparentorderChanged();
            }
        }
        private global::System.Int32 _parentorder;
        partial void OnparentorderChanging(global::System.Int32 value);
        partial void OnparentorderChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("McPermissionsModel", "FK__PrInherit__child__123EB7A3", "PrEntry")]
        public PrEntry PrEntry
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PrEntry>("McPermissionsModel.FK__PrInherit__child__123EB7A3", "PrEntry").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PrEntry>("McPermissionsModel.FK__PrInherit__child__123EB7A3", "PrEntry").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PrEntry> PrEntryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PrEntry>("McPermissionsModel.FK__PrInherit__child__123EB7A3", "PrEntry");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PrEntry>("McPermissionsModel.FK__PrInherit__child__123EB7A3", "PrEntry", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("McPermissionsModel", "FK__PrInherit__paren__1332DBDC", "PrEntry")]
        public PrEntry PrEntry1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PrEntry>("McPermissionsModel.FK__PrInherit__paren__1332DBDC", "PrEntry").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PrEntry>("McPermissionsModel.FK__PrInherit__paren__1332DBDC", "PrEntry").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PrEntry> PrEntry1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PrEntry>("McPermissionsModel.FK__PrInherit__paren__1332DBDC", "PrEntry");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PrEntry>("McPermissionsModel.FK__PrInherit__paren__1332DBDC", "PrEntry", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="McPermissionsModel", Name="PrPermission")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PrPermission : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PrPermission object.
        /// </summary>
        /// <param name="permid">Initial value of the permid property.</param>
        /// <param name="permstring">Initial value of the permstring property.</param>
        /// <param name="entryid">Initial value of the entryid property.</param>
        public static PrPermission CreatePrPermission(global::System.Int32 permid, global::System.String permstring, global::System.Int32 entryid)
        {
            PrPermission prPermission = new PrPermission();
            prPermission.permid = permid;
            prPermission.permstring = permstring;
            prPermission.entryid = entryid;
            return prPermission;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 permid
        {
            get
            {
                return _permid;
            }
            set
            {
                if (_permid != value)
                {
                    OnpermidChanging(value);
                    ReportPropertyChanging("permid");
                    _permid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("permid");
                    OnpermidChanged();
                }
            }
        }
        private global::System.Int32 _permid;
        partial void OnpermidChanging(global::System.Int32 value);
        partial void OnpermidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String permstring
        {
            get
            {
                return _permstring;
            }
            set
            {
                OnpermstringChanging(value);
                ReportPropertyChanging("permstring");
                _permstring = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("permstring");
                OnpermstringChanged();
            }
        }
        private global::System.String _permstring;
        partial void OnpermstringChanging(global::System.String value);
        partial void OnpermstringChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 entryid
        {
            get
            {
                return _entryid;
            }
            set
            {
                OnentryidChanging(value);
                ReportPropertyChanging("entryid");
                _entryid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("entryid");
                OnentryidChanged();
            }
        }
        private global::System.Int32 _entryid;
        partial void OnentryidChanging(global::System.Int32 value);
        partial void OnentryidChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("McPermissionsModel", "FK__PrPermiss__entry__6E01572D", "PrEntries")]
        public PrEntry PrEntry
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PrEntry>("McPermissionsModel.FK__PrPermiss__entry__6E01572D", "PrEntries").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PrEntry>("McPermissionsModel.FK__PrPermiss__entry__6E01572D", "PrEntries").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PrEntry> PrEntryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PrEntry>("McPermissionsModel.FK__PrPermiss__entry__6E01572D", "PrEntries");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PrEntry>("McPermissionsModel.FK__PrPermiss__entry__6E01572D", "PrEntries", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="McPermissionsModel", Name="PrTrack")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PrTrack : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PrTrack object.
        /// </summary>
        /// <param name="trackid">Initial value of the trackid property.</param>
        /// <param name="trackname">Initial value of the trackname property.</param>
        /// <param name="worldid">Initial value of the worldid property.</param>
        public static PrTrack CreatePrTrack(global::System.Int32 trackid, global::System.String trackname, global::System.Int32 worldid)
        {
            PrTrack prTrack = new PrTrack();
            prTrack.trackid = trackid;
            prTrack.trackname = trackname;
            prTrack.worldid = worldid;
            return prTrack;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 trackid
        {
            get
            {
                return _trackid;
            }
            set
            {
                if (_trackid != value)
                {
                    OntrackidChanging(value);
                    ReportPropertyChanging("trackid");
                    _trackid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("trackid");
                    OntrackidChanged();
                }
            }
        }
        private global::System.Int32 _trackid;
        partial void OntrackidChanging(global::System.Int32 value);
        partial void OntrackidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String trackname
        {
            get
            {
                return _trackname;
            }
            set
            {
                OntracknameChanging(value);
                ReportPropertyChanging("trackname");
                _trackname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("trackname");
                OntracknameChanged();
            }
        }
        private global::System.String _trackname;
        partial void OntracknameChanging(global::System.String value);
        partial void OntracknameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 worldid
        {
            get
            {
                return _worldid;
            }
            set
            {
                OnworldidChanging(value);
                ReportPropertyChanging("worldid");
                _worldid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("worldid");
                OnworldidChanged();
            }
        }
        private global::System.Int32 _worldid;
        partial void OnworldidChanging(global::System.Int32 value);
        partial void OnworldidChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("McPermissionsModel", "FK__PrTrackGr__track__07C12930", "PrTrackGroup")]
        public EntityCollection<PrTrackGroup> PrTrackGroups
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PrTrackGroup>("McPermissionsModel.FK__PrTrackGr__track__07C12930", "PrTrackGroup");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PrTrackGroup>("McPermissionsModel.FK__PrTrackGr__track__07C12930", "PrTrackGroup", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("McPermissionsModel", "FK__PrTracks__worldi__02084FDA", "PrWorld")]
        public PrWorld PrWorld
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PrWorld>("McPermissionsModel.FK__PrTracks__worldi__02084FDA", "PrWorld").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PrWorld>("McPermissionsModel.FK__PrTracks__worldi__02084FDA", "PrWorld").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PrWorld> PrWorldReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PrWorld>("McPermissionsModel.FK__PrTracks__worldi__02084FDA", "PrWorld");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PrWorld>("McPermissionsModel.FK__PrTracks__worldi__02084FDA", "PrWorld", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="McPermissionsModel", Name="PrTrackGroup")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PrTrackGroup : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PrTrackGroup object.
        /// </summary>
        /// <param name="trackgroupid">Initial value of the trackgroupid property.</param>
        /// <param name="trackid">Initial value of the trackid property.</param>
        /// <param name="gid">Initial value of the gid property.</param>
        /// <param name="groupOrder">Initial value of the groupOrder property.</param>
        public static PrTrackGroup CreatePrTrackGroup(global::System.Int32 trackgroupid, global::System.Int32 trackid, global::System.Int32 gid, global::System.Int32 groupOrder)
        {
            PrTrackGroup prTrackGroup = new PrTrackGroup();
            prTrackGroup.trackgroupid = trackgroupid;
            prTrackGroup.trackid = trackid;
            prTrackGroup.gid = gid;
            prTrackGroup.groupOrder = groupOrder;
            return prTrackGroup;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 trackgroupid
        {
            get
            {
                return _trackgroupid;
            }
            set
            {
                if (_trackgroupid != value)
                {
                    OntrackgroupidChanging(value);
                    ReportPropertyChanging("trackgroupid");
                    _trackgroupid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("trackgroupid");
                    OntrackgroupidChanged();
                }
            }
        }
        private global::System.Int32 _trackgroupid;
        partial void OntrackgroupidChanging(global::System.Int32 value);
        partial void OntrackgroupidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 trackid
        {
            get
            {
                return _trackid;
            }
            set
            {
                OntrackidChanging(value);
                ReportPropertyChanging("trackid");
                _trackid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("trackid");
                OntrackidChanged();
            }
        }
        private global::System.Int32 _trackid;
        partial void OntrackidChanging(global::System.Int32 value);
        partial void OntrackidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 gid
        {
            get
            {
                return _gid;
            }
            set
            {
                OngidChanging(value);
                ReportPropertyChanging("gid");
                _gid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("gid");
                OngidChanged();
            }
        }
        private global::System.Int32 _gid;
        partial void OngidChanging(global::System.Int32 value);
        partial void OngidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 groupOrder
        {
            get
            {
                return _groupOrder;
            }
            set
            {
                OngroupOrderChanging(value);
                ReportPropertyChanging("groupOrder");
                _groupOrder = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("groupOrder");
                OngroupOrderChanged();
            }
        }
        private global::System.Int32 _groupOrder;
        partial void OngroupOrderChanging(global::System.Int32 value);
        partial void OngroupOrderChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("McPermissionsModel", "FK__PrTrackGrou__gid__08B54D69", "PrEntry")]
        public PrEntry PrEntry
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PrEntry>("McPermissionsModel.FK__PrTrackGrou__gid__08B54D69", "PrEntry").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PrEntry>("McPermissionsModel.FK__PrTrackGrou__gid__08B54D69", "PrEntry").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PrEntry> PrEntryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PrEntry>("McPermissionsModel.FK__PrTrackGrou__gid__08B54D69", "PrEntry");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PrEntry>("McPermissionsModel.FK__PrTrackGrou__gid__08B54D69", "PrEntry", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("McPermissionsModel", "FK__PrTrackGr__track__07C12930", "PrTrack")]
        public PrTrack PrTrack
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PrTrack>("McPermissionsModel.FK__PrTrackGr__track__07C12930", "PrTrack").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PrTrack>("McPermissionsModel.FK__PrTrackGr__track__07C12930", "PrTrack").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PrTrack> PrTrackReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PrTrack>("McPermissionsModel.FK__PrTrackGr__track__07C12930", "PrTrack");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PrTrack>("McPermissionsModel.FK__PrTrackGr__track__07C12930", "PrTrack", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="McPermissionsModel", Name="PrWorld")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PrWorld : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PrWorld object.
        /// </summary>
        /// <param name="worldid">Initial value of the worldid property.</param>
        /// <param name="worldname">Initial value of the worldname property.</param>
        public static PrWorld CreatePrWorld(global::System.Int32 worldid, global::System.String worldname)
        {
            PrWorld prWorld = new PrWorld();
            prWorld.worldid = worldid;
            prWorld.worldname = worldname;
            return prWorld;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 worldid
        {
            get
            {
                return _worldid;
            }
            set
            {
                if (_worldid != value)
                {
                    OnworldidChanging(value);
                    ReportPropertyChanging("worldid");
                    _worldid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("worldid");
                    OnworldidChanged();
                }
            }
        }
        private global::System.Int32 _worldid;
        partial void OnworldidChanging(global::System.Int32 value);
        partial void OnworldidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String worldname
        {
            get
            {
                return _worldname;
            }
            set
            {
                OnworldnameChanging(value);
                ReportPropertyChanging("worldname");
                _worldname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("worldname");
                OnworldnameChanged();
            }
        }
        private global::System.String _worldname;
        partial void OnworldnameChanging(global::System.String value);
        partial void OnworldnameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("McPermissionsModel", "FK__PrEntries__world__68487DD7", "PrEntries")]
        public EntityCollection<PrEntry> PrEntries
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PrEntry>("McPermissionsModel.FK__PrEntries__world__68487DD7", "PrEntries");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PrEntry>("McPermissionsModel.FK__PrEntries__world__68487DD7", "PrEntries", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("McPermissionsModel", "FK__PrTracks__worldi__02084FDA", "PrTrack")]
        public EntityCollection<PrTrack> PrTracks
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PrTrack>("McPermissionsModel.FK__PrTracks__worldi__02084FDA", "PrTrack");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PrTrack>("McPermissionsModel.FK__PrTracks__worldi__02084FDA", "PrTrack", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("McPermissionsModel", "FK__PrWorldBa__world__72C60C4A", "PrWorldBase")]
        public PrWorldBase PrWorldBase
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PrWorldBase>("McPermissionsModel.FK__PrWorldBa__world__72C60C4A", "PrWorldBase").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PrWorldBase>("McPermissionsModel.FK__PrWorldBa__world__72C60C4A", "PrWorldBase").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PrWorldBase> PrWorldBaseReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PrWorldBase>("McPermissionsModel.FK__PrWorldBa__world__72C60C4A", "PrWorldBase");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PrWorldBase>("McPermissionsModel.FK__PrWorldBa__world__72C60C4A", "PrWorldBase", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="McPermissionsModel", Name="PrWorldBase")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PrWorldBase : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PrWorldBase object.
        /// </summary>
        /// <param name="worldid">Initial value of the worldid property.</param>
        public static PrWorldBase CreatePrWorldBase(global::System.Int32 worldid)
        {
            PrWorldBase prWorldBase = new PrWorldBase();
            prWorldBase.worldid = worldid;
            return prWorldBase;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 worldid
        {
            get
            {
                return _worldid;
            }
            set
            {
                if (_worldid != value)
                {
                    OnworldidChanging(value);
                    ReportPropertyChanging("worldid");
                    _worldid = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("worldid");
                    OnworldidChanged();
                }
            }
        }
        private global::System.Int32 _worldid;
        partial void OnworldidChanging(global::System.Int32 value);
        partial void OnworldidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> defaultid
        {
            get
            {
                return _defaultid;
            }
            set
            {
                OndefaultidChanging(value);
                ReportPropertyChanging("defaultid");
                _defaultid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("defaultid");
                OndefaultidChanged();
            }
        }
        private Nullable<global::System.Int32> _defaultid;
        partial void OndefaultidChanging(Nullable<global::System.Int32> value);
        partial void OndefaultidChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("McPermissionsModel", "FK__PrWorldBa__defau__73BA3083", "PrEntry")]
        public PrEntry PrEntry
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PrEntry>("McPermissionsModel.FK__PrWorldBa__defau__73BA3083", "PrEntry").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PrEntry>("McPermissionsModel.FK__PrWorldBa__defau__73BA3083", "PrEntry").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PrEntry> PrEntryReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PrEntry>("McPermissionsModel.FK__PrWorldBa__defau__73BA3083", "PrEntry");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PrEntry>("McPermissionsModel.FK__PrWorldBa__defau__73BA3083", "PrEntry", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("McPermissionsModel", "FK__PrWorldBa__world__72C60C4A", "PrWorld")]
        public PrWorld PrWorld
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PrWorld>("McPermissionsModel.FK__PrWorldBa__world__72C60C4A", "PrWorld").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PrWorld>("McPermissionsModel.FK__PrWorldBa__world__72C60C4A", "PrWorld").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PrWorld> PrWorldReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PrWorld>("McPermissionsModel.FK__PrWorldBa__world__72C60C4A", "PrWorld");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PrWorld>("McPermissionsModel.FK__PrWorldBa__world__72C60C4A", "PrWorld", value);
                }
            }
        }

        #endregion
    }

    #endregion
    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="McPermissionsModel", Name="get_groupPlayers_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class get_groupPlayers_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new get_groupPlayers_Result object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        public static get_groupPlayers_Result Createget_groupPlayers_Result(global::System.String name)
        {
            get_groupPlayers_Result get_groupPlayers_Result = new get_groupPlayers_Result();
            get_groupPlayers_Result.name = name;
            return get_groupPlayers_Result;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();

        #endregion
    }

    #endregion
    
}
